-- Supabase Schema for Donation Platform

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default categories
insert into public.categories (name) values 
  ('إلكترونيات'),
  ('ملابس'),
  ('أثاث'),
  ('كتب'),
  ('ألعاب'),
  ('رياضة'),
  ('إكسسوارات'),
  ('أخرى');

-- 3. Create Profiles Table (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone_number text,
  address text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Donations Table
create type donation_condition as enum ('جديد', 'مستعمل جيد', 'مستعمل');
create type donation_status as enum ('متاح', 'محجوز', 'تم التسليم');

create table public.donations (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category_id bigint references public.categories(id) on delete set null,
  donor_id uuid references public.profiles(id) on delete cascade not null,
  condition donation_condition not null default 'مستعمل جيد'::donation_condition,
  status donation_status not null default 'متاح'::donation_status,
  images text[] default array[]::text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create Donation Requests Table
create type request_status as enum ('قيد الانتظار', 'مقبول', 'مرفوض');

create table public.donation_requests (
  id bigint generated by default as identity primary key,
  donation_id bigint references public.donations(id) on delete cascade not null,
  requester_id uuid references public.profiles(id) on delete cascade not null,
  delivery_address text not null,
  delivery_phone text not null,
  message text,
  status request_status not null default 'قيد الانتظار'::request_status,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (donation_id, requester_id) -- Prevent duplicate requests from same user for same item
);

-- 6. Setup Row Level Security (RLS)

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.donations enable row level security;
alter table public.donation_requests enable row level security;

-- Profiles Policies
create policy "Public profiles are viewable by everyone."
  on profiles for select using (true);
create policy "Users can insert their own profile."
  on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile."
  on profiles for update using (auth.uid() = id);

-- Categories Policies
create policy "Categories are viewable by everyone."
  on categories for select using (true);

-- Donations Policies
create policy "Donations are viewable by everyone."
  on donations for select using (true);
create policy "Authenticated users can insert donations."
  on donations for insert with check (auth.role() = 'authenticated' and auth.uid() = donor_id);
create policy "Users can update their own donations."
  on donations for update using (auth.uid() = donor_id);
create policy "Users can delete their own donations."
  on donations for delete using (auth.uid() = donor_id);

-- Donation Requests Policies
create policy "Users can view their own requests."
  on donation_requests for select using (auth.uid() = requester_id);
create policy "Donor can view requests for their donations."
  on donation_requests for select using (
    exists (
      select 1 from donations
      where donations.id = donation_requests.donation_id
      and donations.donor_id = auth.uid()
    )
  );
create policy "Authenticated users can create requests."
  on donation_requests for insert with check (auth.role() = 'authenticated' and auth.uid() = requester_id);
create policy "Users can update their own requests (like canceling)."
  on donation_requests for update using (auth.uid() = requester_id);
create policy "Donor can update request status."
  on donation_requests for update using (
    exists (
      select 1 from donations
      where donations.id = donation_requests.donation_id
      and donations.donor_id = auth.uid()
    )
  );

-- 7. Triggers and Functions

-- Function to handle new user signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Trigger for updating 'updated_at' columns
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
    before update on profiles
    for each row execute procedure update_updated_at_column();

create trigger update_donations_updated_at
    before update on donations
    for each row execute procedure update_updated_at_column();

create trigger update_donation_requests_updated_at
    before update on donation_requests
    for each row execute procedure update_updated_at_column();

-- Function to automatically update donation status when a request is accepted
create or replace function update_donation_status_on_request_acceptance()
returns trigger as $$
begin
  if new.status = 'مقبول'::request_status and old.status = 'قيد الانتظار'::request_status then
    update public.donations
    set status = 'محجوز'::donation_status
    where id = new.donation_id;
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_request_accepted
  after update on donation_requests
  for each row execute procedure update_donation_status_on_request_acceptance();

-- 8. Storage bucket for donation images
insert into storage.buckets (id, name, public) values ('donation-images', 'donation-images', true) on conflict do nothing;

create policy "Images are publicly accessible."
  on storage.objects for select using (bucket_id = 'donation-images');
create policy "Authenticated users can upload images."
  on storage.objects for insert with check (bucket_id = 'donation-images' and auth.role() = 'authenticated');
create policy "Users can update their own images."
  on storage.objects for update using (bucket_id = 'donation-images' and auth.uid() = owner);
create policy "Users can delete their own images."
  on storage.objects for delete using (bucket_id = 'donation-images' and auth.uid() = owner);
